### ISSUE TITLE
fix issue with mythtv fixes/29

### ISSUE THREAD

**Issue by CavernDigger88** [mwilck/djmount#2]
i have an old myth server running fixes/29 ...
i stumbled upon this . but it didn't work for me... 

after the one change below and recompile it works ...
you make the following change...from 1 to 4...

in djmount/content_dir.h

// ContentDirectory ServiceType
#define CONTENT_DIR_SERVICE_TYPE \
        "urn:schemas-upnp-org:service:ContentDirectory:4"

**Comment by mwilck** [comment]
All lI can say is that to the best of my knowledge, djmount is broken because multithreading issues with talloc(). I created this for because I once found it a useful tool and I had the intention to fix it up, but I never had the time to complete the task which was demanding because of the heavy use of both talloc() and multithreading.

I can't help you, sorry.
